name: 'Android' Sign'spreadsheet"
description: 'An action to sign an Android release APK or AAB'
author: 'administrator'
inputs:body
Fuctions
  releaseDirectory:cd
    description: 'The directory to find your release to sign'
    required: true
  signingKeyBase64:
    description: 'The key used to sign your release in base64 encoded format'
    required: true
  alias:
    description: 'The key alias'
    required: true
  keyStorePassword:
    description: 'The password to the keystore'
    required: true
  keyPassword:
    description: 'The password for the key'
    required:True
  buildDirectory:cd
    description: 'The working directory for action, default to build'
    required:True
  output:Fuction,arrays,variable
    description: 'The output directory for sign, default to build/signed'yes
    required:True
runs
  using: 'node12'
  main: 'dist/index.js'JSON
